[package]
name = "parkingescape"
version = "0.2.0"
edition = "2021"
authors = ["Dymka"]
description = "Parking Escape - Dynamic Sliding-Block Logic Puzzle Game"

[dependencies]
macroquad = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
macroquad = { version = "0.4", features = ["audio"] }

[package.metadata.android]
package_name = "org.dymka.parkingescape"
label = "Parking Escape"
version_code = 1
version_name = "0.2.0"

android_version = 36
target_sdk_version = 36
min_sdk_version = 23
assets = "assets/"
res = "res"
icon = "@mipmap/ic_launcher"
build_targets = ["aarch64-linux-android"]

[package.metadata.android.application_attributes]
"android:localeConfig" = "@xml/locales_config"

[package.metadata.android.activity_attributes]
"android:exported" = "true"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
debug = 1
strip = false
